shamefullyHoist: true
minimumReleaseAge: 1500

overrides:
  esbuild: 0.28.2

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/vitest-plugin@1.1.10'
  - miniflare@5.20260915.0-alpha
  - wrangler@4.132.0
  - miniflare@4.20260625.0
  - wrangler@4.105.0
