-- Generated by `drizzle-kit generate --name better_auth_account_issuer`, then
-- expanded to backfill populated tables before enforcing Better Auth 1.7's
-- required issuer column.
ALTER TABLE `account` ADD `issuer` text;
--> statement-breakpoint
-- Credential identity is based on the immutable user ID. Do not derive an
-- issuer or account ID from mutable email/profile data.
UPDATE `account`
SET `issuer` = CASE
  WHEN `provider_id` = 'credential' THEN 'local:credential'
  ELSE 'local:oauth:' || `provider_id`
END,
`account_id` = CASE
  WHEN `provider_id` = 'credential' THEN `user_id`
  ELSE `account_id`
END
WHERE `issuer` IS NULL;
--> statement-breakpoint
-- SQLite cannot make an existing column NOT NULL in place, so rebuild only
-- after the backfill has populated every row.
CREATE TABLE `account_new` (
  `id` text PRIMARY KEY NOT NULL,
  `issuer` text NOT NULL,
  `account_id` text NOT NULL,
  `provider_id` text NOT NULL,
  `user_id` text NOT NULL,
  `access_token` text,
  `refresh_token` text,
  `id_token` text,
  `access_token_expires_at` integer,
  `refresh_token_expires_at` integer,
  `scope` text,
  `password` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `account_new` (`id`, `issuer`, `account_id`, `provider_id`, `user_id`, `access_token`, `refresh_token`, `id_token`, `access_token_expires_at`, `refresh_token_expires_at`, `scope`, `password`, `created_at`, `updated_at`)
SELECT `id`, `issuer`, `account_id`, `provider_id`, `user_id`, `access_token`, `refresh_token`, `id_token`, `access_token_expires_at`, `refresh_token_expires_at`, `scope`, `password`, `created_at`, `updated_at`
FROM `account`;
--> statement-breakpoint
DROP TABLE `account`;
--> statement-breakpoint
ALTER TABLE `account_new` RENAME TO `account`;
--> statement-breakpoint
CREATE UNIQUE INDEX `account_issuer_accountId_uidx` ON `account` (`issuer`, `account_id`);
--> statement-breakpoint
CREATE INDEX `account_userId_idx` ON `account` (`user_id`);
